In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import time

# Train Dataset

In [ ]:
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [ ]:
# Load Dataset
application_train = pd.read_csv("application_train.csv")
bureau = pd.read_csv("bureau.csv")
bureau_balance = pd.read_csv("bureau_balance.csv")
previous_application = pd.read_csv("previous_application.csv")
pos_cash = pd.read_csv("POS_CASH_balance.csv")
installments = pd.read_csv("installments_payments.csv")
credit_card = pd.read_csv("credit_card_balance.csv")

In [ ]:
# Display the head of each DataFrame
dataframes = [application_train, bureau, bureau_balance, previous_application, pos_cash, installments, credit_card]
dataframe_names = ['application_train', 'bureau', 'bureau_balance', 'previous_application', 'pos_cash', 'installments', 'credit_card']

for df, name in zip(dataframes, dataframe_names):
    print(f"DataFrame: {name}")
    display(df.head(1))
    print("\n")

DataFrame: application_train

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.018801,-9461,-637,-3648.0,-2120,NaN,1,1,0,1,1,0,Laborers,1.0,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.083037,0.262949,0.139376,0.0247,0.0369,0.9722,0.6192,0.0143,0.0,0.069,0.0833,0.125,0.0369,0.0202,0.019,0.0,0.0,0.0252,0.0383,0.9722,0.6341,0.0144,0.0,0.069,0.0833,0.125,0.0377,0.022,0.0198,0.0,0.0,0.025,0.0369,0.9722,0.6243,0.0144,0.0,0.069,0.0833,0.125,0.0375,0.0205,0.0193,0.0,0.0,reg oper account,block of flats,0.0149,"Stone, brick",No,2.0,2.0,2.0,2.0,-1134.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0

DataFrame: bureau

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.0,0.0,NaN,0.0,Consumer credit,-131,NaN

DataFrame: bureau_balance

   SK_ID_BUREAU  MONTHS_BALANCE STATUS
0       5715448               0      C

DataFrame: previous_application

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,FLAG_LAST_APPL_PER_CONTRACT,NFLAG_LAST_APPL_IN_DAY,RATE_DOWN_PAYMENT,RATE_INTEREST_PRIMARY,RATE_INTEREST_PRIVILEGED,NAME_CASH_LOAN_PURPOSE,NAME_CONTRACT_STATUS,DAYS_DECISION,NAME_PAYMENT_TYPE,CODE_REJECT_REASON,NAME_TYPE_SUITE,NAME_CLIENT_TYPE,NAME_GOODS_CATEGORY,NAME_PORTFOLIO,NAME_PRODUCT_TYPE,CHANNEL_TYPE,SELLERPLACE_AREA,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,271877,Consumer loans,1730.43,17145.0,17145.0,0.0,17145.0,SATURDAY,15,Y,1,0.0,0.182832,0.867336,XAP,Approved,-73,Cash through the bank,XAP,NaN,Repeater,Mobile,POS,XNA,Country-wide,35,Connectivity,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0

DataFrame: pos_cash

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,1803195,182943,-31,48.0,45.0,Active,0,0

DataFrame: installments

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT
0,1054186,161674,1.0,6,-1180.0,-1187.0,6948.36,6948.36

DataFrame: credit_card

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,AMT_PAYMENT_CURRENT,AMT_PAYMENT_TOTAL_CURRENT,AMT_RECEIVABLE_PRINCIPAL,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,2562384,378907,-6,56.97,135000,0.0,877.5,0.0,877.5,1700.325,1800.0,1800.0,0.0,0.0,0.0,0.0,1,0.0,1.0,35.0,Active,0,0

# Merge Dataset

In [ ]:
# bureau dataset

# Aggregation per SK_ID_CURR
bureau_agg = bureau.groupby('SK_ID_CURR').agg({
    'SK_ID_BUREAU': 'count',  # Number of external loans
    'AMT_CREDIT_SUM': ['sum', 'mean'],  # Total and average credit
    'DAYS_CREDIT': ['min', 'max'],  # First and last recorded credit
    'CREDIT_ACTIVE': lambda x: (x == 'Active').sum(),  # Active loans count
}).reset_index()

# Rename columns
bureau_agg.columns = ['SK_ID_CURR', 'NUM_BUREAU_LOANS', 'SUM_CREDIT', 'AVG_CREDIT', 'FIRST_CREDIT_DAYS', 'LAST_CREDIT_DAYS', 'ACTIVE_LOANS']

In [ ]:
bureau_agg.head()

,SK_ID_CURR,NUM_BUREAU_LOANS,SUM_CREDIT,AVG_CREDIT,FIRST_CREDIT_DAYS,LAST_CREDIT_DAYS,ACTIVE_LOANS
0,100001,7,1453365.000,207623.571429,-1572,-49,3
1,100002,8,865055.565,108131.945625,-1437,-103,2
2,100003,4,1017400.500,254350.125000,-2586,-606,1
3,100004,2,189037.800,94518.900000,-1326,-408,0
4,100005,3,657126.000,219042.000000,-373,-62,2

In [ ]:
# Merge with main dataset
application_train = application_train.merge(bureau_agg, on='SK_ID_CURR', how='left')

In [ ]:
# bureau_balance dataset

# Aggregate per loan (SK_ID_BUREAU)
bureau_balance_agg = bureau_balance.groupby('SK_ID_BUREAU').agg({
    'MONTHS_BALANCE': ['min', 'max'],  # First and last recorded month
    'STATUS': lambda x: (x.astype(str) > '0').sum()  # Overdue months count
}).reset_index()

# Rename columns
bureau_balance_agg.columns = ['SK_ID_BUREAU', 'FIRST_MONTH_BALANCE', 'LAST_MONTH_BALANCE', 'OVERDUE_MONTHS']

# Merge with bureau dataset
bureau = bureau.merge(bureau_balance_agg, on='SK_ID_BUREAU', how='left')

In [ ]:
bureau_balance_agg.head()

   SK_ID_BUREAU  FIRST_MONTH_BALANCE  LAST_MONTH_BALANCE  OVERDUE_MONTHS
0       5001709                  -96                   0              97
1       5001710                  -82                   0              78
2       5001711                   -3                   0               1
3       5001712                  -18                   0               9
4       5001713                  -21                   0              22

In [ ]:
# Aggregate per SK_ID_CURR
bureau_final_agg = bureau.groupby('SK_ID_CURR').agg({
    'OVERDUE_MONTHS': 'sum',  # Total overdue months
    'FIRST_MONTH_BALANCE': 'min',  # First recorded month
    'LAST_MONTH_BALANCE': 'max',  # Last recorded month
}).reset_index()

In [ ]:
# Merge with main dataset
application_train = application_train.merge(bureau_final_agg, on='SK_ID_CURR', how='left')

In [ ]:
# previous_application dataset

# Aggregate per SK_ID_CURR
previous_agg = previous_application.groupby('SK_ID_CURR').agg({
    'SK_ID_PREV': 'count',  # Number of previous loans
    'AMT_CREDIT': ['sum', 'mean'],  # Total and average credit
    'DAYS_DECISION': 'min',  # Most recent loan decision
}).reset_index()

# Rename columns
previous_agg.columns = ['SK_ID_CURR', 'NUM_PREV_LOANS', 'SUM_PREV_CREDIT', 'AVG_PREV_CREDIT', 'RECENT_LOAN_DAYS']

In [ ]:
previous_agg.head()

,SK_ID_CURR,NUM_PREV_LOANS,SUM_PREV_CREDIT,AVG_PREV_CREDIT,RECENT_LOAN_DAYS
0,100001,1,23787.0,23787.00,-1740
1,100002,1,179055.0,179055.00,-606
2,100003,3,1452573.0,484191.00,-2341
3,100004,1,20106.0,20106.00,-815
4,100005,2,40153.5,20076.75,-757

In [ ]:
# Merge with main dataset
application_train = application_train.merge(previous_agg, on='SK_ID_CURR', how='left')

In [ ]:
# POS_CASH_balance dataset

# Aggregate per SK_ID_PREV
pos_cash_agg = pos_cash.groupby('SK_ID_PREV').agg({
    'MONTHS_BALANCE': ['min', 'max'],  # First and last recorded month
}).reset_index()

# Fix Multi-Level Column Names
pos_cash_agg.columns = ['_'.join(col).strip() if isinstance(col, tuple) else col for col in pos_cash_agg.columns]

# Rename the key column properly
pos_cash_agg.rename(columns={'SK_ID_PREV_': 'SK_ID_PREV'}, inplace=True)

In [ ]:
pos_cash_agg.head()

   SK_ID_PREV  MONTHS_BALANCE_min  MONTHS_BALANCE_max
0     1000001                 -10                  -8
1     1000002                 -54                 -50
2     1000003                  -4                  -1
3     1000004                 -29                 -22
4     1000005                 -56                 -46

In [ ]:
# Merge with previous_application before aggregating per SK_ID_CURR
previous_application = previous_application.merge(pos_cash_agg, on='SK_ID_PREV', how='left')

# Aggregate per SK_ID_CURR
pos_cash_final_agg = previous_application.groupby('SK_ID_CURR').agg({
    'MONTHS_BALANCE_min': 'min',  # First recorded month
    'MONTHS_BALANCE_max': 'max',  # Last recorded month
}).reset_index()

In [ ]:
# Merge with main dataset
application_train = application_train.merge(pos_cash_final_agg, on='SK_ID_CURR', how='left')

In [ ]:
# installments_payments dataset

# Aggregate per SK_ID_PREV
installments_agg = installments.groupby('SK_ID_PREV').agg({
    'AMT_PAYMENT': 'mean',  # Average installment payment
    'DAYS_ENTRY_PAYMENT': lambda x: (x > 0).sum()  # Count of late payments
}).reset_index()

In [ ]:
installments_agg.head()

   SK_ID_PREV   AMT_PAYMENT  DAYS_ENTRY_PAYMENT
0     1000001  34221.712500                   0
1     1000002   9308.891250                   0
2     1000003   4951.350000                   0
3     1000004   4789.022143                   0
4     1000005  13365.609545                   0

In [ ]:
# Merge with previous_application
previous_application = previous_application.merge(installments_agg, on='SK_ID_PREV', how='left')

# Aggregate per SK_ID_CURR
installments_final_agg = previous_application.groupby('SK_ID_CURR').agg({
    'AMT_PAYMENT': 'mean',  # Average installment payment
    'DAYS_ENTRY_PAYMENT': 'sum'  # Total late payments
}).reset_index()

In [ ]:
# Merge with main dataset
application_train = application_train.merge(installments_final_agg, on='SK_ID_CURR', how='left')

In [ ]:
application_train.shape

(307511, 139)